loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../]
    modules: [
      "haystack_experimental.components.agents.agent",
      "haystack_experimental.components.agents.agent.human_in_the_loop_agent.dataclasses",
      "haystack_experimental.components.agents.agent.human_in_the_loop_agent.policies",
      "haystack_experimental.components.agents.agent.human_in_the_loop_agent.protocol",
      "haystack_experimental.components.agents.agent.human_in_the_loop_agent.strategies",
      "haystack_experimental.components.agents.agent.human_in_the_loop_agent.user_interfaces",
    ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Tool-using agents with provider-agnostic chat model support.
  category_slug: haystack-api
  title: Agents
  slug: experimental-agents-api
  order: 2
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: experimental_agents_api.md
