loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../]
    modules: ["haystack_experimental.evaluation.harness.evaluation_harness",
              "haystack_experimental.evaluation.harness.rag.harness",
              "haystack_experimental.evaluation.harness.rag.parameters"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Evaluation harness for Haystack.
  category_slug: experiments-api
  title: Evaluation Harness
  slug: evaluation-harness-api
  order: 40
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: evaluation_harness_api.md
