loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../]
    modules: ["haystack_experimental.super_components.indexers.sentence_transformers_document_indexer"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Pipelines wrapped as components.
  category_slug: experiments-api
  title: SuperComponents
  slug: experimental-supercomponents-api
  order: 50
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: experimental_supercomponents_api.md
