loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../]
    modules: ["haystack_experimental.components.tools.tool_invoker"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeIntegrationRenderer
  excerpt: ToolInvoker invokes Tools based on a ChatMessage containing tool calls
  category_slug: experiments-api
  title: Tool Invoker
  slug: tool-invoker-api
  order: 110
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: tool_invoker_api.md
