fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast   # checks Python syntax
    - id: check-json  # checks JSON syntax
    - id: check-merge-conflict  # checks for no merge conflict strings
    - id: check-shebang-scripts-are-executable  # checks all shell scripts have executable permissions
    - id: check-toml  # checks TOML syntax
    - id: check-yaml  # checks YAML syntax
    - id: end-of-file-fixer  # checks there is a newline at the end of the file
    - id: mixed-line-ending  # normalizes line endings
    - id: no-commit-to-branch  # prevents committing to main
    - id: trailing-whitespace  # trims trailing whitespace
      args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0
  hooks:
    - id: ruff
      args: ["--config=pyproject.toml", "--select=ASYNC,C4,C90,E501,EXE,F,INT,PERF,PL,Q,SIM,SLOT,T10,W,YTT,I,A001,A002,A003,D102,D103,D209,D205,D213,D417,D419", "--ignore=F401,PERF203,PERF401,PLR1714,PLR5501,PLW0603,PLW1510,PLW2901,SIM108,SIM115,SIM118", "--line-length=120", "--target-version=py38"]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: [
          "--ignore-words-list=ans,astroid,nd,ned,nin,ue,rouge,ist",
          "--skip=test/nodes/*,test/others/*,test/samples/*,e2e/*",
          "--quiet-level=3"
        ]
    additional_dependencies:
      - tomli

- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
  - id: actionlint-docker
    args: ["-ignore", "SC2102"]

- repo: local
  hooks:
  -   id: pylint
      name: pylint
      entry: pylint
      language: python
      types: [python]
      args: ["--rcfile=pyproject.toml"]
