# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

import pytest
from haystack import Document, Pipeline
from haystack.components.retrievers import InMemoryBM25Retriever
from haystack.components.writers import DocumentWriter
from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.document_stores.types import DuplicatePolicy

from haystack_experimental.components.retrievers.multi_query_keyword_retriever import MultiQueryKeywordRetriever


class TestMultiQueryKeywordRetriever:

    @pytest.fixture
    def sample_documents(self):
        return [
            Document(content="Renewable energy is energy that is collected from renewable resources."),
            Document(content="Solar energy is a type of green energy that is harnessed from the sun."),
            Document(content="Wind energy is another type of green energy that is generated by wind turbines."),
            Document(content="Hydropower is a form of renewable energy using the flow of water to generate electricity."),
            Document(content="Geothermal energy is heat that comes from the sub-surface of the earth."),
            Document(content="Fossil fuels, such as coal, oil, and natural gas, are non-renewable energy sources."),
            Document(content="Nuclear energy is produced through nuclear reactions, typically using uranium or plutonium as fuel."),
        ]

    @pytest.fixture
    def document_store_with_docs(self, sample_documents):
        document_store = InMemoryDocumentStore()
        doc_writer = DocumentWriter(document_store=document_store, policy=DuplicatePolicy.SKIP)
        doc_writer.run(documents=sample_documents)
        return document_store

    def test_init_with_default_parameters(self):
        in_memory_retriever = InMemoryBM25Retriever(document_store=InMemoryDocumentStore())
        retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever)
        
        assert retriever.retriever == in_memory_retriever
        assert retriever.top_k == 3
        assert retriever.filters is None
        assert retriever.max_workers == 3

    def test_init_with_custom_parameters(self):
        in_memory_retriever = InMemoryBM25Retriever(document_store=InMemoryDocumentStore())
        filters = {"category": "energy"}
        retriever = MultiQueryKeywordRetriever(
            retriever=in_memory_retriever,
            top_k=5,
            filters=filters,
            max_workers=2
        )
        
        assert retriever.retriever == in_memory_retriever
        assert retriever.top_k == 5
        assert retriever.filters == filters
        assert retriever.max_workers == 2

    def test_run_with_multiple_queries(self, document_store_with_docs):
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever, top_k=2)
        
        queries = ["renewable energy", "solar power", "wind turbines"]
        result = multi_retriever.run(queries=queries)
        
        assert "documents" in result
        assert len(result["documents"]) > 0
        assert all(isinstance(doc, Document) for doc in result["documents"])
        scores = [doc.score for doc in result["documents"] if doc.score is not None]
        assert scores == sorted(scores, reverse=True)

    def test_run_with_deduplication(self, document_store_with_docs):
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever, top_k=3)
        
        # queries that might return the same documents
        queries = ["renewable energy", "green energy", "sustainable energy"]
        result = multi_retriever.run(queries=queries)
        
        assert "documents" in result
        # check that no duplicate content exists
        contents = [doc.content for doc in result["documents"]]
        assert len(contents) == len(set(contents))

    def test_run_with_custom_top_k(self, document_store_with_docs):
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever, top_k=1)
        
        result = multi_retriever.run(queries=["energy"], top_k=5)
        
        assert "documents" in result
        assert len(result["documents"]) <= 5

    def test_parallel_execution(self, document_store_with_docs):
        """Test that multiple queries are executed in parallel."""
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever, max_workers=2)
        
        queries = ["renewable energy", "solar power", "wind energy", "geothermal"]
        result = multi_retriever.run(queries=queries)
        
        assert "documents" in result
        assert len(result["documents"]) > 0

    def test_to_dict(self, document_store_with_docs):
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(
            retriever=in_memory_retriever,
            top_k=5,
            filters={"category": "test"},
            max_workers=2
        )
        
        result = multi_retriever.to_dict()
        
        assert "type" in result
        assert "init_parameters" in result
        assert result["init_parameters"]["top_k"] == 5
        assert result["init_parameters"]["filters"] == {"category": "test"}
        assert result["init_parameters"]["max_workers"] == 2
        assert "retriever" in result["init_parameters"]
        assert result["init_parameters"]["retriever"]["type"] == "haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever"

    def test_from_dict(self):
        data = {
            'type': 'haystack_experimental.components.retrievers.multi_query_retriever.MultiQueryKeywordRetriever',
            'init_parameters': {
                'retriever': {
                    'type': 'haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever',
                    'init_parameters': {
                        'document_store': {
                            'type': 'haystack.document_stores.in_memory.document_store.InMemoryDocumentStore',
                            'init_parameters': {
                                'bm25_tokenization_regex': '(?u)\\b\\w\\w+\\b',
                                'bm25_algorithm': 'BM25L',
                                'bm25_parameters': {},
                                'embedding_similarity_function': 'dot_product',
                                'index': '88144fa9-6e45-4e5d-8647-4c4002d8b6db',
                                'return_embedding': True}
                        },
                        'filters': None,
                        'top_k': 10,
                        'scale_score': False,
                        'filter_policy': 'replace'}},
             'top_k': 3,
             'filters': None,
             'max_workers': 3}}

        result = MultiQueryKeywordRetriever.from_dict(data)

        assert isinstance(result, MultiQueryKeywordRetriever)
        assert result.retriever.__class__.__name__ == "InMemoryBM25Retriever"
        assert result.top_k == 3
        assert result.filters == {"category": "test"}
        assert result.max_workers == 3

    def test_pipeline_integration(self, document_store_with_docs):
        """Test integration with Haystack Pipeline."""
        in_memory_retriever = InMemoryBM25Retriever(document_store=document_store_with_docs)
        multi_retriever = MultiQueryKeywordRetriever(retriever=in_memory_retriever)
        
        pipeline = Pipeline()
        pipeline.add_component("multi_retriever", multi_retriever)
        
        result = pipeline.run(data={"multi_retriever": {"queries": ["renewable energy", "solar power"]}})
        
        assert "multi_retriever" in result
        assert "documents" in result["multi_retriever"]
        assert len(result["multi_retriever"]["documents"]) > 0
