name: Project release on PyPi

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  HATCH_VERSION: "1.16.5"

jobs:
  release-on-pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Hatch
        run: pip install --uploaded-prior-to=P1D hatch==${{ env.HATCH_VERSION }}

      - name: Build Haystack Experimental
        run: hatch build

      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          VERSION: ${{ github.ref_name }}
        if: always()
        uses: act10ns/slack@2f01f46db9f41c75a04d93c6ce310bc51db7cb50 # v2
        with:
          status: ${{ job.status }}
          channel: "#haystack-notifications"
          config: .github/config/pypi-release-slack-notification.yml
